export const SET_SHOWS = 'SET_SHOWS';
export const SET_CURRENT_SHOW = 'SET_CURRENT_SHOW';
export const SET_CURRENT_EPISODE = 'SET_CURRENT_EPISODE';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_DURATION = 'SET_DURATION';